<a href="https://colab.research.google.com/github/plindma/ST-554-Project1/blob/main/ST554_Project_1_Task_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Project 1 - Task 3

In [1]:
!pip install ucimlrepo

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2026.1.4)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7

In [45]:
import ucimlrepo as uci
import pandas as pd

air_quality = uci.fetch_ucirepo(id=360)

In [5]:
air_quality.data.features

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,3/10/2004,18:00:00,2.6,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578
1,3/10/2004,19:00:00,2.0,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255
2,3/10/2004,20:00:00,2.2,1402,88,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502
3,3/10/2004,21:00:00,2.2,1376,80,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867
4,3/10/2004,22:00:00,1.6,1272,51,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9352,4/4/2005,10:00:00,3.1,1314,-200,13.5,1101,472,539,190,1374,1729,21.9,29.3,0.7568
9353,4/4/2005,11:00:00,2.4,1163,-200,11.4,1027,353,604,179,1264,1269,24.3,23.7,0.7119
9354,4/4/2005,12:00:00,2.4,1142,-200,12.4,1063,293,603,175,1241,1092,26.9,18.3,0.6406
9355,4/4/2005,13:00:00,2.1,1003,-200,9.5,961,235,702,156,1041,770,28.3,13.5,0.5139
9356,4/4/2005,14:00:00,2.2,1071,-200,11.9,1047,265,654,168,1129,816,28.5,13.1,0.5028

In [11]:
air_quality_df = air_quality.data.features

In [37]:
# Remove rows where C6H6(GT), CO(GT), T, RH, or AH is -200
cleaned_aq_df = air_quality_df[(air_quality_df['C6H6(GT)'] != -200)  &
                               (air_quality_df['CO(GT)'] != -200) &
                               (air_quality_df['T'] != -200) &
                               (air_quality_df['RH'] != -200) &
                               (air_quality_df['AH'] != -200) ]
cleaned_aq_df

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,3/10/2004,18:00:00,2.6,1360,150,11.9,1046,166,1056,113,1692,1268,13.6,48.9,0.7578
1,3/10/2004,19:00:00,2.0,1292,112,9.4,955,103,1174,92,1559,972,13.3,47.7,0.7255
2,3/10/2004,20:00:00,2.2,1402,88,9.0,939,131,1140,114,1555,1074,11.9,54.0,0.7502
3,3/10/2004,21:00:00,2.2,1376,80,9.2,948,172,1092,122,1584,1203,11.0,60.0,0.7867
4,3/10/2004,22:00:00,1.6,1272,51,6.5,836,131,1205,116,1490,1110,11.2,59.6,0.7888
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9352,4/4/2005,10:00:00,3.1,1314,-200,13.5,1101,472,539,190,1374,1729,21.9,29.3,0.7568
9353,4/4/2005,11:00:00,2.4,1163,-200,11.4,1027,353,604,179,1264,1269,24.3,23.7,0.7119
9354,4/4/2005,12:00:00,2.4,1142,-200,12.4,1063,293,603,175,1241,1092,26.9,18.3,0.6406
9355,4/4/2005,13:00:00,2.1,1003,-200,9.5,961,235,702,156,1041,770,28.3,13.5,0.5139
9356,4/4/2005,14:00:00,2.2,1071,-200,11.9,1047,265,654,168,1129,816,28.5,13.1,0.5028

In [68]:
# Convert 'Date' column to datetime objects to ensure correct chronological sorting
cleaned_aq_df['Date_datetime'] = pd.to_datetime(cleaned_aq_df['Date'])

# Get unique sorted datetime objects
unique_dates = cleaned_aq_df['Date_datetime'].sort_values().unique()

# Create a mapping from each unique date to a 1-based integer day
date_to_day_map = {date: i + 1 for i, date in enumerate(unique_dates)}

# Apply the mapping to create the new 'Day' column
cleaned_aq_df['Day'] = cleaned_aq_df['Date_datetime'].map(date_to_day_map)

In [69]:
daily_avg_df = cleaned_aq_df.groupby('Date') \
              .mean(numeric_only=True) \
              .sort_values(by='Day') \
              [['C6H6(GT)','CO(GT)','T','RH','AH','Day']]

daily_avg_df

            C6H6(GT)    CO(GT)          T         RH        AH    Day
Date
3/10/2004   8.450000  1.966667  12.033333  54.900000  0.765633    1.0
3/11/2004   8.269565  2.239130   9.826087  64.230435  0.777039    2.0
3/12/2004  12.177273  2.804545  11.618182  50.190909  0.665164    3.0
3/13/2004  11.121739  2.695652  13.121739  50.682609  0.733013    4.0
3/14/2004   9.830435  2.469565  16.182609  48.317391  0.849209    5.0
...              ...       ...        ...        ...       ...    ...
3/31/2005   5.220833  1.387500  17.550000  50.083333  0.951917  343.0
4/1/2005    3.526087  1.108696  16.026087  35.404348  0.631135  344.0
4/2/2005    2.529167  0.854167  15.483333  32.225000  0.546167  345.0
4/3/2005    4.316667  1.141667  18.383333  33.695833  0.617583  346.0
4/4/2005    8.985714  2.078571  17.328571  41.842857  0.721250  347.0

[347 rows x 6 columns]